[env:transmitter_hw]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
board_build.flash_mode = dout
board_build.f_flash = 40000000L
build_src_filter = +<transmitter_pro.cpp>
lib_deps =
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit SSD1306 @ ^2.5.9
    adafruit/Adafruit GFX Library @ ^1.11.9
    bblanchon/ArduinoJson @ ^6.21.3

[env:receiver_hw]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.arduino.memory_type = qio_opi ; For 16MB Flash / 8MB PSRAM
build_src_filter = +<receiver_pro.cpp>
lib_deps =
    zinggjm/GxEPD2 @ ^1.5.5
    adafruit/Adafruit GFX Library @ ^1.11.9
    bblanchon/ArduinoJson @ ^6.21.3

[env:transmitter2_esp8266]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_src_filter = +<transmitter2_esp8266.cpp>
lib_deps =
    adafruit/DHT sensor library @ ^1.4.6
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
    bblanchon/ArduinoJson @ ^6.21.3
